---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: test-source
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/mohammedafzal0702/git-test.git

